### ISSUE TITLE
How do you compare the performance of DFF and Accel?

### ISSUE THREAD

**Issue by mornfairy** [SamvitJ/Accel#1]
Your paper uses a novel idea in video object segmentation. As far as I know，DFF is a model of video object detection. How to compare them？ Did you train DFF with a new dataset or some adjustments have been made？I would appreciate it if you could answer my questions. Thank you！

**Comment by lxtGH** [comment]
DFF is just a way of warping deep feature in video frame work. So it can be used for many video tasks.

**Comment by SamvitJ** [comment]
Deep Feature Flow reported results on both the tasks of video object detection and semantic segmentation. They explicitly released code for the former, but also pointed out a pathway to implement the latter.
